// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPSN7N_5nTNdUDAmLcW_xTr4voKiSVjtg',
    appId: '1:922919718051:web:ae7dfe0366b1d99d5cc316',
    messagingSenderId: '922919718051',
    projectId: 'social-app-8f692',
    authDomain: 'social-app-8f692.firebaseapp.com',
    storageBucket: 'social-app-8f692.firebasestorage.app',
    measurementId: 'G-XF4CZ3SM5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvC_OA2W-qsPc7L4CdDIHMFp7FZC8tF5s',
    appId: '1:922919718051:android:a2b7710785d505e25cc316',
    messagingSenderId: '922919718051',
    projectId: 'social-app-8f692',
    storageBucket: 'social-app-8f692.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANfiAUnhKqJNQj2C-emfnfkoVeSn7kEQc',
    appId: '1:922919718051:ios:7b1f457aca2bdaf35cc316',
    messagingSenderId: '922919718051',
    projectId: 'social-app-8f692',
    storageBucket: 'social-app-8f692.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANfiAUnhKqJNQj2C-emfnfkoVeSn7kEQc',
    appId: '1:922919718051:ios:7b1f457aca2bdaf35cc316',
    messagingSenderId: '922919718051',
    projectId: 'social-app-8f692',
    storageBucket: 'social-app-8f692.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPSN7N_5nTNdUDAmLcW_xTr4voKiSVjtg',
    appId: '1:922919718051:web:2c42354a9fa17cde5cc316',
    messagingSenderId: '922919718051',
    projectId: 'social-app-8f692',
    authDomain: 'social-app-8f692.firebaseapp.com',
    storageBucket: 'social-app-8f692.firebasestorage.app',
    measurementId: 'G-DTEVTES241',
  );
}
